server {
    listen 80;
    listen [::]:80;
    server_name __MIRROR_DOMAIN__;

    root __MIRROR_WEB_ROOT__;
    index index.html;
    charset utf-8;

    access_log /var/log/nginx/__MIRROR_DOMAIN__.access.log;
    error_log /var/log/nginx/__MIRROR_DOMAIN__.error.log;

    location = /status/json {
        proxy_pass http://__YUKI_LISTEN__/api/v1/metas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /status/ {
        try_files $uri $uri/ =404;
    }

    location / {
        autoindex on;
        autoindex_exact_size off;
        try_files $uri $uri/ =404;
    }
}
