[%main%]
root = /srv/mirror/www/
urlbase = /

[%alias%]
libreoffice = tdf

# Configs from mirrorz/genisolist
!include ../z-genisolist/includes/distro.ini
!include ../z-genisolist/includes/os/**/*.ini
!include ../z-genisolist/includes/app/**/*.ini
