[%main%]
root = /srv/repo/
urlbase = /

[%alias%]
libreoffice = tdf

# Configs from mirrorz/genisolist
!include ../z-genisolist/includes/distro.ini
!include includes/os/**/*.ini
!include includes/app/**/*.ini
